name: ngd_datatable
description: This plugin is made to display a data table on Angular Dart platform. Currently it support a simple data table with or without server processing.
version: 0.1.11
homepage: https://icemanbsi.github.io/ngd-datatable/

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  ngdart: ^7.1.1
  ngrouter: ^3.1.1
  intl: ^0.17.0

dev_dependencies:
  ngtest: ^4.1.1
  build_runner: ^2.1.5
  build_test: ^2.1.4
  build_web_compilers: ^3.2.1
  pedantic: ^1.8.0
  test: ^1.6.0
